#!/bin/bash

############################
# 日志函数
############################
MAIN_LOG="/tmp/metatube-fnos.log"
APP_LOG="/tmp/metatube-app.log"

log_message() {
    local msg="$1"
    local ts
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    echo "${ts} [METATUBE] ${msg}" | tee -a "${MAIN_LOG}"
}

log_message "==============配置开始=============="
log_message "==============配置开始=============="

exit 0